# render.yaml
services:
  - type: web
    name: quants-shop-bots
    env: python
    region: frankfurt
    # ВАЖНО: добавлен флаг --only-binary=:all:
    buildCommand: pip install --only-binary=:all: -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        generateValue: true
    autoDeploy: true
    plan: free